deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - echo "34.64.153.45 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIASruNcrTObNMz0z2zNrUeFwBNx+7Y5wLjwmXUIuA7Tc" >> ~/.ssh/known_hosts

  script:
    - ssh elice@34.64.153.45 "cd /home/elice/gonggan_mazzip && git pull"
    - 'echo "$SUDO_PASSWORD" | sudo -S make re'
  only:
    - dev
    - feature-BE-cicd
