deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - ssh elice@34.64.153.45 "cd /home/elice/gonggan_mazzip && git pull"
    - 'echo "$SUDO_PASSWORD" | sudo -S make deploy'
  only:
    - dev
    - feature-BE-cicd
