deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan 34.64.153.45 >> ~/.ssh/known_hosts

  script:
    - ssh elice@34.64.153.45 'echo "hello deploy!"'
    - ssh elice@34.64.153.45 "cd /home/elice/gonggan_mazzip && git pull"
    - 'echo "$SUDO_PASSWORD" | sudo -S make re'
  only:
    - dev
    - feature-BE-cicd
