deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - echo '# 34.64.153.45:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
34.64.153.45 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLJrQ1Q9uUCL2wF4TboMO+fyLdGIUlRRtKMs0O1KSN9nl5wMvxHoVuICH5R52w0a3Qfg6qzlmITmN6Q3hAHqbOk=
# 34.64.153.45:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
34.64.153.45 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDopYZjNUmVE7XS0xTSu0HXxKRgU0UivWPWKx5ZSb/j54GAIQmTX6ChZ2pjg2jG91Qy23GoizppB0fIvn4kPszfPMtTgH/q4tW/u/0sxFTZtnwweYevnZ0LCM9LwmI7uHSxW36sAi19zC88dgW31T5kK7gkvuz9ugAG7MyWeUuzryzyKEaEwJzAoXQ7ajlfMMfUSyZQVtHVz36ROtoxqIFK/t87LyMUd4z6+HP7qyn4SiyAHcnHDlHllyqhMLOm7LkjDFwvIa5NFywezJYkXO8TUVrZIWIwrHSUKaA1JXY93zHBaK1XSHkaF1vkrjtVJ72TzF4YeMQ+JcVvFXl2L92+Xh5NAot6lCSVqyD+LLIKMub8+N49buC+aVcUypoNcnCPOSFudPOz9M6xI+R364+OMQykAhS4ZYj7ksq9s3NkXiroYPlgWpGe5OF17p+e4b3IpobZZGCjs9XB7qvl87wJR/I7vh76GT95VvGAY+gJr1KQXrGHBqK236m/Kmr4Cr0=
# 34.64.153.45:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
34.64.153.45 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIASruNcrTObNMz0z2zNrUeFwBNx+7Y5wLjwmXUIuA7Tc
# 34.64.153.45:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
# 34.64.153.45:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5'

  script:
    - ssh elice@34.64.153.45 "cd /home/elice/gonggan_mazzip && git pull"
    - 'echo "$SUDO_PASSWORD" | sudo -S make deploy'
  only:
    - dev
    - feature-BE-cicd
