version: "3"

services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017"
    volumes:
      - db_data:/data/db

  nodejs:
    build:
      context: ../
      dockerfile: ./deployment/nodejs/Dockerfile

    container_name: nodejs
    restart: always
    ports:
      - "5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27017/my-db
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
